# Generated by Django 5.0.2 on 2024-04-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
    ]
